# Travis build file
# .travis.yml


language: cpp

compiler:
  - gcc
  - clang

# qt5.1 build with travis needs a ppa (ubuntu 12.04)
# http://stackoverflow.com/questions/29721240/ci-for-qt-app-build-with-different-qt-versions
before_install:
    - sudo add-apt-repository --yes ppa:beineri/opt-qt511
    - sudo apt-get update -qq
    - sudo apt-get install -y qt51-meta-minimal qt51serialport libgl1-mesa-dev libusb-1.0-0-dev

script:
 - source /opt/qt51/bin/qt51-env.sh
 - qmake
 - make
